name: 🧾 Pull Request — SafeHaven
description: Submit a PR to improve SafeHaven with features, fixes, or updates.
title: "PR: "
labels: ["pull request"]
assignees: []

body:
  - type: input
    id: issue
    attributes:
      label: "📌 Related Issue"
      description: "Link the related issue (e.g., Fixes #12)."
      placeholder: "Fixes #issue-number"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Description of Changes"
      description: "Describe your changes and their purpose."
      placeholder: "Refactored navbar responsiveness / Added new section..."
    validations:
      required: true

  - type: checkboxes
    id: change_type
    attributes:
      label: "Type of Change"
      options:
        - label: "🐛 Bug Fix"
        - label: "🔧Feature Modification"
        - label: "✨ New Feature"
        - label: "🧹 Maintenance / Cleanup / Documentation Update"
        - label: "🎨 UI/UX or Design Update"
        - label: "📘 Resource / Content Addition"
        - label: "Other"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "📸 Screenshots / Video"
      placeholder: "Attach visuals if your PR affects UI or layout."

  - type: checkboxes
    id: checklist
    attributes:
      label: "✅ Checklist "
      options:
        - label: "I've read the CONTRIBUTING.md guidelines."
        - label: "My code follows the project's conventions."
        - label: "I've linked the related issue correctly."
        - label: "I've tested my changes locally."
        - label: "I've added/updated documentation or comments."
        - label: "My PR title follows the branch & commit naming conventions."
        - label: "My changes introduce no new warnings or errors."
        - label: "I've performed a self-review of my code."
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: "💬 Additional Notes (Optional)"
      placeholder: "Add any context, dependencies, or questions for reviewers."
